repos:
  - repo: local
    hooks:
      - id: generate-openapi
        name: Generate OpenAPI YAML
        entry: python generate_openapi.py
        language: system
        types: [python]
        files: ^main\.py$|^your_app_folder/